const AVATARS = ['🧑‍🦲','👩‍🦰','👩','🧕','👩🏻‍🦳','👨🏽','🧑‍🦱','👱','🧔','🧑‍🦰'];
const MARKERS = [{id:0,color:'#8e44ad',cost:0},{id:1,color:'#c0392b',cost:15000},{id:2,color:'#2980b9',cost:15000},{id:3,color:'#27ae60',cost:15000}];
const DAILY_REWARDS = [{icon:'💵',text:'500'},{icon:'💵',text:'1000'},{icon:'🪙',text:'10'},{icon:'💵',text:'1500'},{icon:'🪙',text:'30'},{icon:'💵',text:'3000'},{icon:'🪙',text:'45'}];
const SHOP_ITEMS = [{bills:500,coins:10},{bills:1000,coins:15},{bills:2000,coins:29},{bills:4000,coins:49},{bills:10000,coins:79}];
const DRAW_INTERVAL = 4000;
const NICKNAMES = {1:'Кол',3:'Троечка',11:'Барабанные палочки',12:'Дюжина',13:'Чёртова дюжина',22:'Гуси-лебеди',25:'Четвертак',44:'Стульчики',50:'Полтинник',66:'Валенки',77:'Топорики',89:'Дедушкин сосед',90:'Дедушка'};
let uid = localStorage.getItem('loto_uid');
let user = null;
let currentRoomId = null;
let multiSyncInterval = null;
let heartbeatInterval = null;
let currentAdminPassword = '';
let soundOn = true;
let gameState = null;
let lastMultiDrawn = 0;
let lastNotificationSignature = '';

function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;}
function speakDrumNumber(n){if(!soundOn||!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(NICKNAMES[n]||String(n));u.lang='ru-RU';u.rate=1.1;window.speechSynthesis.speak(u);}
function playNotificationSound(){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C();const o=c.createOscillator();const g=c.createGain();o.frequency.value=700;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.01,c.currentTime+.25);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.25);}catch(e){}}
async function api(url,options){const r=await fetch(url,options);let data={};try{data=await r.json();}catch{}if(!r.ok)throw Object.assign(new Error(data.error||'Ошибка запроса'),{status:r.status,data});return data;}

async function loadUser(){try{const data=await api(`/api/state?uid=${encodeURIComponent(uid||'')}`);uid=data.uid;localStorage.setItem('loto_uid',uid);user=data;renderMenu();if(user.pendingGifts?.length)showGiftNotifications(user.pendingGifts);}catch(e){if(e.status===403){document.body.innerHTML='<h1 style="text-align:center;margin-top:100px;color:white">Вы заблокированы 🚫</h1>';}}}
async function saveUser(patch){if(!user)return;try{const data=await api('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,...patch})});user=data.user;renderMenu();if(document.getElementById('screen-game')?.classList.contains('active'))renderGameCurrency();return true;}catch(e){alert(e.message);return false;}}
function renderMenu(){if(!user)return;const av=document.getElementById('menu-avatar-emoji');if(av)av.textContent=AVATARS[user.avatar]||AVATARS[0];const nm=document.getElementById('menu-avatar-name');if(nm)nm.innerHTML=`${esc(user.name)} ${user.isVip?'<span class="vip-gold-text">👑 VIP</span>':''}`;document.getElementById('cur-bills').textContent=user.bills;document.getElementById('cur-coins').textContent=user.coins;}
function renderGameCurrency(){document.getElementById('game-cur-bills').textContent=user.bills;document.getElementById('game-cur-coins').textContent=user.coins;}
function openModal(name){const el=document.getElementById('modal-'+name);if(!el)return;el.classList.remove('hidden');if(name==='daily')renderDaily();if(name==='leaderboard')renderLeaderboard();if(name==='shop')renderShop();if(name==='marker')renderMarkers();if(name==='profile')renderProfile();}
function closeModal(name){document.getElementById('modal-'+name)?.classList.add('hidden');}
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));

function renderDaily(){const grid=document.getElementById('daily-grid');if(!grid)return;grid.innerHTML='';const today=(Number(user.dailyStreak)||0)%7;const can=Date.now()-Number(user.lastClaim||0)>=86400000;DAILY_REWARDS.forEach((r,i)=>{const c=document.createElement('div');c.className='daily-cell'+(i<today?' claimed':'')+(i===today?' today':'');c.innerHTML=`<div class="d-num">${i+1}</div><div class="d-icon">${r.icon}</div><div>${r.text}</div>`;grid.appendChild(c);});const b=document.getElementById('daily-claim');b.disabled=!can;b.textContent=can?'Получить награду':'Уже получено';}
document.getElementById('daily-claim').addEventListener('click',async()=>{try{const d=await api('/api/dailyreward/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid})});user=d.user;renderMenu();renderDaily();playNotificationSound();}catch(e){alert(e.message);}});
async function renderLeaderboard(){const list=document.getElementById('leaderboard-list');if(!list)return;list.innerHTML='Загрузка...';try{const data=await api('/api/leaderboard');list.innerHTML='';data.forEach((r,i)=>{const d=document.createElement('div');d.className='lb-row'+(r.uid===uid?' me':'');d.innerHTML=`<div class="lb-rank">${i+1}</div><div class="lb-emoji">${AVATARS[r.avatar]||'🙂'}</div><div class="lb-name">${esc(r.name)} ${r.isVip?'👑':''}</div><div class="lb-score">${r.score}</div>`;list.appendChild(d);});}catch(e){list.textContent=e.message;}}
function renderShop(){const list=document.getElementById('shop-list');if(!list)return;list.innerHTML='';SHOP_ITEMS.forEach(item=>{const row=document.createElement('div');row.className='shop-row';row.innerHTML=`<span>${item.bills} 💵</span><button class="btn small-buy">${item.coins} 🪙</button>`;row.querySelector('button').addEventListener('click',async()=>{if(user.bills<item.bills)return alert('Недостаточно 💵');try{const d=await api('/api/shop/buy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,bills:item.bills,coins:item.coins})});user=d.user;renderMenu();renderShop();}catch(e){alert(e.message);}});list.appendChild(row);});}
function renderMarkers(){const grid=document.getElementById('marker-grid');if(!grid)return;grid.innerHTML='';user.unlockedMarkers=user.unlockedMarkers||[0];MARKERS.forEach(m=>{const owned=user.unlockedMarkers.includes(m.id);const c=document.createElement('div');c.className='marker-cell'+(user.marker===m.id?' selected':'')+(!owned?' locked':'');c.innerHTML=`<div class="m-dot" style="background:${m.color}"></div><div class="m-cost">${owned?(user.marker===m.id?'Выбран':'Выбрать'):m.cost+' 💵 🔒'}</div>`;c.addEventListener('click',async()=>{try{const d=await api('/api/marker/buy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,markerId:m.id})});user=d.user;renderMenu();renderMarkers();}catch(e){alert(e.message);}});grid.appendChild(c);});}

function renderProfile(){const input=document.getElementById('profile-name-input');input.value=user.name;document.getElementById('profile-current-avatar').textContent=AVATARS[user.avatar]||AVATARS[0];const grid=document.getElementById('avatar-grid');grid.innerHTML='';let picked=user.avatar;AVATARS.forEach((emoji,i)=>{const c=document.createElement('div');c.className='avatar-cell'+(i===picked?' selected':'');c.textContent=emoji;c.onclick=()=>{picked=i;grid.querySelectorAll('.avatar-cell').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');document.getElementById('profile-current-avatar').textContent=emoji;};grid.appendChild(c);});document.getElementById('profile-save').onclick=async()=>{const name=input.value.trim();if(!name)return alert('Ник не пустой!');if(await saveUser({name,avatar:picked}))closeModal('profile');};}

function generateTicket(){const rows=[[],[],[]];let ok=false;for(let attempt=0;attempt<20000&&!ok;attempt++){rows.forEach(r=>{r.length=0;const a=[0,1,2,3,4,5,6,7,8];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}r.push(...a.slice(0,5));});const counts=Array(9).fill(0);rows.forEach(r=>r.forEach(c=>counts[c]++));ok=counts.every(x=>x>=1&&x<=3);}if(!ok)return generateTicket();const grid=Array.from({length:3},()=>Array(9).fill(null));for(let c=0;c<9;c++){const rs=rows.map((r,i)=>r.includes(c)?i:-1).filter(i=>i>=0).sort((a,b)=>a-b);const start=c===0?1:c*10,end=c===8?90:c*10+9;const pool=[];for(let n=start;n<=end;n++)pool.push(n);pool.sort(()=>Math.random()-.5);const nums=pool.slice(0,rs.length).sort((a,b)=>a-b);rs.forEach((r,i)=>grid[r][c]=nums[i]);}return grid;}
function checkWin(mode,tickets,marks){if(mode==='A')return tickets.some((t,ti)=>t.flat().filter(Number.isInteger).every((n,idx)=>marks[ti].flat().filter(Boolean).length>=0&&isMarkedValue(n,ti,marks)));if(mode==='B')return tickets.some((t,ti)=>t.some((row,r)=>{const ns=row.filter(Number.isInteger);return ns.length&&ns.every(n=>isMarkedValue(n,ti,marks));}));if(mode==='C')return tickets.some((t,ti)=>{const ns=t[2].filter(Number.isInteger);return ns.length&&ns.every(n=>isMarkedValue(n,ti,marks));});return false;}
function isMarkedValue(n,ti,marks){const ticket=gameState.tickets[ti];for(let r=0;r<3;r++)for(let c=0;c<9;c++)if(ticket[r][c]===n)return !!marks[ti][r][c];return false;}
function markedValues(){const out=[];if(!gameState)return out;gameState.tickets.forEach((t,ti)=>t.forEach((row,r)=>row.forEach((n,c)=>{if(Number.isInteger(n)&&gameState.marks[ti][r][c])out.push(n);})));return [...new Set(out)];}
function renderTickets(){const container=document.getElementById('tickets-container');if(!container||!gameState)return;container.innerHTML='';const marker=(MARKERS.find(m=>m.id===user.marker)||MARKERS[0]).color;gameState.tickets.forEach((ticket,ti)=>{const table=document.createElement('table');table.className='ticket';ticket.forEach((row,ri)=>{const tr=document.createElement('tr');row.forEach((v,ci)=>{const td=document.createElement('td');if(v===null){td.className='empty';}else{td.textContent=v;if(gameState.drawn.includes(v)&&user.isVip)gameState.marks[ti][ri][ci]=true;if(gameState.marks[ti][ri][ci]){td.classList.add('marked');td.style.background=marker;}else if(gameState.drawn.includes(v))td.classList.add('drawn-not-marked');td.onclick=()=>{if(gameState.drawn.includes(v)&&!gameState.marks[ti][ri][ci]){gameState.marks[ti][ri][ci]=true;renderTickets();maybeClaimMultiWin();}};}tr.appendChild(td);});table.appendChild(tr);});container.appendChild(table);});}
function updateHistoryUI(){const h=document.getElementById('history-numbers');if(!h||!gameState)return;h.innerHTML=gameState.drawn.slice(-5).reverse().map(n=>`<span class="history-item">${n}</span>`).join(' ');}
function showNumber(n){const el=document.getElementById('drum-number');el.textContent=n;el.style.animation='none';void el.offsetHeight;el.style.animation='popDrum .4s ease-out';document.getElementById('drum-nickname').textContent=NICKNAMES[n]||'';}
function startGame(mode,numCards){document.getElementById('screen-menu').classList.remove('active');document.getElementById('screen-game').classList.add('active');document.getElementById('room-chat-container').classList.add('hidden');renderGameCurrency();document.getElementById('game-player-avatar').textContent=AVATARS[user.avatar]||AVATARS[0];document.getElementById('game-player-name').textContent=user.name;const tickets=[],marks=[];for(let i=0;i<numCards;i++){tickets.push(generateTicket());marks.push(Array.from({length:3},()=>Array(9).fill(false)));}gameState={mode,tickets,marks,drawn:[],timer:null,finished:false};renderTickets();gameState.timer=setInterval(()=>{if(gameState.drawn.length>=90){clearInterval(gameState.timer);return;}let n;do n=Math.floor(1+Math.random()*90);while(gameState.drawn.includes(n));gameState.drawn.push(n);showNumber(n);speakDrumNumber(n);updateHistoryUI();renderTickets();if(checkWin(mode,tickets,marks)){clearInterval(gameState.timer);triggerWinEffects(mode==='A'?'🎉 Вы победили!':mode==='B'?'🎉 Короткое Лото — вы закрыли строку!':'🎉 Три на Три — вы закрыли нижнюю строку!');}},DRAW_INTERVAL);}
function triggerWinEffects(msg){playNotificationSound();setTimeout(()=>alert(msg),300);}

function openMultiplayer(){document.getElementById('modal-multiplayer').classList.remove('hidden');document.getElementById('multi-create-block').classList.remove('hidden');document.getElementById('multi-join-block').classList.remove('hidden');document.getElementById('multi-waiting-block').classList.add('hidden');}
document.getElementById('btn-open-multiplayer').addEventListener('click',openMultiplayer);
document.getElementById('btn-close-multiplayer').addEventListener('click',()=>{closeModal('multiplayer');stopMultiTimers();});
document.getElementById('btn-multi-create').addEventListener('click',async()=>{try{stopMultiTimers();const maxPlayers=Number(document.getElementById('multi-max-players').value);const stake=Number(document.getElementById('multi-stake').value);const mode=document.querySelector('input[name="game-mode"]:checked')?.value||'A';const d=await api('/api/room/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,maxPlayers,stake,mode})});user.bills=d.userBalance;renderMenu();startWaiting(d.roomId);}catch(e){alert(e.message);}});
document.getElementById('btn-multi-join').addEventListener('click',async()=>{try{stopMultiTimers();const roomId=document.getElementById('multi-room-id').value.trim();if(!roomId)return alert('Введите код стола');const d=await api('/api/room/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId})});user.bills=d.userBalance;renderMenu();startWaiting(roomId);}catch(e){alert(e.message);}});
function startWaiting(roomId){currentRoomId=String(roomId);document.getElementById('multi-create-block').classList.add('hidden');document.getElementById('multi-join-block').classList.add('hidden');document.getElementById('multi-waiting-block').classList.remove('hidden');document.getElementById('txt-table-code').textContent=currentRoomId;syncRoom();multiSyncInterval=setInterval(syncRoom,1000);heartbeatInterval=setInterval(sendHeartbeat,4000);}
function stopMultiTimers(){if(multiSyncInterval){clearInterval(multiSyncInterval);multiSyncInterval=null;}if(heartbeatInterval){clearInterval(heartbeatInterval);heartbeatInterval=null;}}
async function sendHeartbeat(){if(!currentRoomId)return;try{await api('/api/room/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId})});}catch(e){}}
async function syncRoom(){if(!currentRoomId)return;try{const room=await api(`/api/room/sync?roomId=${encodeURIComponent(currentRoomId)}&uid=${encodeURIComponent(uid)}`);document.getElementById('multi-players-list').innerHTML=room.players.map(p=>`<div>🧑‍💻 ${esc(p.name)} ${p.online?'🟢':'⚪'}</div>`).join('');if(room.status==='playing'){document.getElementById('modal-multiplayer').classList.add('hidden');startMultiGame(room);}else if(room.status==='finished'||room.status==='cancelled'){stopMultiTimers();alert(room.winnerUid===uid?`🎉 Вы выиграли ${room.payout} 💵!`:'Стол завершён.');location.reload();}}catch(e){if(e.status===404){stopMultiTimers();alert('Стол больше не существует.');location.reload();}}}
function startMultiGame(room){stopMultiTimers();currentRoomId=room.id;document.getElementById('screen-menu').classList.remove('active');document.getElementById('screen-game').classList.add('active');document.getElementById('room-chat-container').classList.remove('hidden');gameState={mode:room.mode,tickets:[room.selfTicket],marks:[Array.from({length:3},()=>Array(9).fill(false))],drawn:room.drawn||[],finished:false,multi:true};lastMultiDrawn=gameState.drawn[gameState.drawn.length-1]||0;renderTickets();if(lastMultiDrawn)showNumber(lastMultiDrawn);updateHistoryUI();multiSyncInterval=setInterval(syncMultiGame,1000);heartbeatInterval=setInterval(sendHeartbeat,4000);}
async function syncMultiGame(){try{const room=await api(`/api/room/sync?roomId=${encodeURIComponent(currentRoomId)}&uid=${encodeURIComponent(uid)}`);if(room.drawn.length>gameState.drawn.length){gameState.drawn=room.drawn;const n=room.drawn[room.drawn.length-1];showNumber(n);speakDrumNumber(n);playNotificationSound();updateHistoryUI();renderTickets();if(n!==lastMultiDrawn)lastMultiDrawn=n;}if(room.chat){document.getElementById('room-chat-messages').innerHTML=room.chat.map(m=>`<div><b>${esc(m.name)}:</b> ${esc(m.text)}</div>`).join('');}if(room.status==='finished'||room.status==='cancelled'){stopMultiTimers();if(room.winnerUid===uid)triggerWinEffects(`🎉 Вы выиграли ${room.payout} 💵!`);else alert(room.status==='cancelled'?'Игра отменена, ставки возвращены.':'Игра завершена.');setTimeout(()=>location.reload(),800);return;}await maybeClaimMultiWin();}catch(e){}}
async function maybeClaimMultiWin(){if(!gameState?.multi||gameState.finished)return;if(!checkWin(gameState.mode,gameState.tickets,gameState.marks))return;gameState.finished=true;try{const d=await api('/api/room/win',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId,marked:markedValues()})});stopMultiTimers();user.bills=d.userBalance;renderMenu();triggerWinEffects(`🎉 Вы выиграли ${d.payout} 💵 и забрали банк!`);setTimeout(()=>location.reload(),1200);}catch(e){gameState.finished=false;}}

document.getElementById('btn-open-global-chat').addEventListener('click',()=>{openModal('global-chat');updateGlobalChat();});document.getElementById('btn-close-global-chat').addEventListener('click',()=>closeModal('global-chat'));
document.getElementById('btn-room-chat-send').addEventListener('click',async()=>{const i=document.getElementById('room-chat-input');if(!i.value.trim())return;try{await api('/api/chat/room/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId,text:i.value.trim()})});i.value='';await syncMultiGame();}catch(e){alert(e.message);}});
document.getElementById('btn-global-chat-send').addEventListener('click',async()=>{const i=document.getElementById('global-chat-input');if(!i.value.trim())return;try{await api('/api/chat/global/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,text:i.value.trim()})});i.value='';updateGlobalChat();}catch(e){alert(e.message);}});
async function updateGlobalChat(){const box=document.getElementById('global-chat-messages');if(!box||document.getElementById('modal-global-chat').classList.contains('hidden'))return;try{const data=await api('/api/chat/global');box.innerHTML=data.map(m=>`<div><b>${esc(m.name)}:</b> ${esc(m.text)}</div>`).join('');box.scrollTop=box.scrollHeight;}catch(e){}}

function showGiftNotifications(gifts){if(!gifts?.length)return;const sig=gifts.map(g=>`${g.at||0}:${g.type||''}:${g.message||''}:${g.bills||0}:${g.coins||0}`).join('|');if(sig===lastNotificationSignature)return;lastNotificationSignature=sig;playNotificationSound();const latest=[...gifts].sort((a,b)=>(a.at||0)-(b.at||0));const g=latest[latest.length-1];const modal=document.getElementById('modal-gift-alert');const icon=document.getElementById('gift-icon');const title=document.getElementById('gift-title');const sender=document.getElementById('gift-sender');const bills=document.getElementById('gift-alert-bills');const coins=document.getElementById('gift-alert-coins');icon.textContent=g.type==='vip'?'👑':g.type==='message'?'💬':'🎁';title.textContent=g.type==='vip'?'VIP-уведомление':g.type==='message'?'SMS от SANI GROUP':'Вам подарок!';sender.textContent=g.message||'Получено от: SANI GROUP';bills.textContent=g.bills?`+${g.bills} 💵`:'';coins.textContent=g.coins?`+${g.coins} 🪙`:'';modal.classList.remove('hidden');document.getElementById('btn-close-gift-alert').onclick=async()=>{modal.classList.add('hidden');try{const d=await api('/api/notifications/clear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid})});user=d.user;renderMenu();}catch(e){}};}

document.getElementById('btn-admin-login').addEventListener('click',()=>openModal('admin'));document.getElementById('btn-close-admin').addEventListener('click',()=>closeModal('admin'));document.getElementById('btn-admin-auth').addEventListener('click',async()=>{currentAdminPassword=document.getElementById('admin-password-input').value;await refreshAdminPanel();});
async function refreshAdminPanel(){try{const players=await api('/api/admin/players',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminPassword:currentAdminPassword})});document.getElementById('admin-auth-block').classList.add('hidden');document.getElementById('admin-panel-block').classList.remove('hidden');renderAdminPlayers(players);}catch(e){alert('Пароль неверный!');}}
function renderAdminPlayers(players){const box=document.getElementById('admin-players-list');box.innerHTML='';players.forEach(p=>{const d=document.createElement('div');d.className='admin-player';d.innerHTML=`<div class="admin-player-head"><b>${esc(p.name)}</b><span>${p.isVip?'👑 VIP':''} ${p.isBanned?'🛑 БАН':''}</span></div><div>💵 ${p.bills} &nbsp; 🪙 ${p.coins}</div><div class="admin-actions"><button data-a="money">💵 Деньги</button><button data-a="coins">🪙 Монеты</button><button data-a="message">💬 SMS</button><button data-a="vip">${p.isVip?'❌ VIP':'👑 VIP'}</button><button data-a="ban">${p.isBanned?'🔓 Разбан':'🔒 Бан'}</button></div>`;d.querySelector('[data-a="money"]').onclick=()=>adminAmount(p.uid,'money');d.querySelector('[data-a="coins"]').onclick=()=>adminAmount(p.uid,'coins');d.querySelector('[data-a="message"]').onclick=()=>adminMessage(p.uid);d.querySelector('[data-a="vip"]').onclick=()=>adminAction(p.uid,'vip',{enabled:!p.isVip});d.querySelector('[data-a="ban"]').onclick=()=>adminAction(p.uid,p.isBanned?'unban':'ban');box.appendChild(d);});let clear=document.getElementById('admin-clear-db');if(clear)clear.onclick=async()=>{if(confirm('Удалить ВСЮ базу игроков и активные столы?'))if(confirm('Последнее подтверждение: восстановить данные будет нельзя. Продолжить?')){await adminAction(null,'clear_database');location.reload();}};}
async function adminAmount(id,action){const amount=Number(prompt(action==='money'?'Сколько 💵 выдать?':'Сколько 🪙 выдать?'));if(!Number.isInteger(amount)||amount<=0)return;await adminAction(id,action,{amount});}
async function adminMessage(id){const message=prompt('Текст SMS игроку:');if(!message?.trim())return;await adminAction(id,'message',{message:message.trim()});}
async function adminAction(id,action,extra={}){try{await api('/api/admin/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminPassword:currentAdminPassword,uid:id,action,...extra})});if(action!=='clear_database')await refreshAdminPanel();}catch(e){alert(e.message);}}

document.getElementById('btn-play').addEventListener('click',()=>openModal('setup'));document.getElementById('setup-start').addEventListener('click',()=>{closeModal('setup');startGame(document.querySelector('input[name="game-mode"]:checked')?.value||'A',3);});
document.getElementById('btn-exit-game').addEventListener('click',async()=>{if(currentRoomId)try{await api('/api/room/leave',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId})});}catch(e){}stopMultiTimers();currentRoomId=null;location.reload();});
document.getElementById('btn-sound').addEventListener('click',e=>{soundOn=!soundOn;e.target.textContent=soundOn?'🔊':'🔇';});
setInterval(()=>{if(document.getElementById('modal-global-chat')&&!document.getElementById('modal-global-chat').classList.contains('hidden'))updateGlobalChat();},2000);
setInterval(loadUser,5000);
loadUser();
