const AVATARS = ['🧑‍🦲','👩‍🦰','👩','🧕','👩🏻‍🦳','👨🏽','🧑‍🦱','👱','🧔','🧑‍🦰'];
const MARKERS = [{id:0,color:'#8e44ad',cost:0},{id:1,color:'#c0392b',cost:15000},{id:2,color:'#2980b9',cost:15000},{id:3,color:'#27ae60',cost:15000}];
const DAILY_REWARDS = [{icon:'💵',text:'500'},{icon:'💵',text:'1000'},{icon:'🪙',text:'10'},{icon:'💵',text:'1500'},{icon:'🪙',text:'30'},{icon:'💵',text:'3000'},{icon:'🪙',text:'45'}];
const SHOP_ITEMS = [];
const BARREL_DESIGNS = [
  {id:0,name:'Классика SANI',icon:'🎱',cost:0},
  {id:1,name:'Royal Gold',icon:'🟡',cost:2500},
  {id:2,name:'Ruby Night',icon:'🔴',cost:3500},
  {id:3,name:'Emerald Elite',icon:'🟢',cost:5000},
  {id:4,name:'Black Onyx',icon:'⚫',cost:6500},
  {id:5,name:'Sapphire',icon:'🔵',cost:8000},
  {id:6,name:'Imperial VIP',icon:'👑',vip:true,cost:0}
];
const CARD_DESIGNS = [
  {id:0,name:'Classic',icon:'🎟️',cost:0},
  {id:1,name:'Royal Gold',icon:'✨',cost:2500},
  {id:2,name:'Ruby Night',icon:'♦️',cost:3500},
  {id:3,name:'Emerald Elite',icon:'♣️',cost:5000},
  {id:4,name:'Black Onyx',icon:'⬛',cost:6500},
  {id:5,name:'Sapphire',icon:'💠',cost:8000},
  {id:6,name:'Imperial VIP',icon:'👑',vip:true,cost:0}
];
const DRAW_INTERVAL = 4000;
const NICKNAMES = {1:'Кол',3:'Троечка',11:'Барабанные палочки',12:'Дюжина',13:'Чёртова дюжина',22:'Гуси-лебеди',25:'Четвертак',44:'Стульчики',50:'Полтинник',66:'Валенки',77:'Топорики',89:'Дедушкин сосед',90:'Дедушка'};
let uid = localStorage.getItem('loto_uid');
let user = null;
let currentRoomId = null;
let multiSyncInterval = null;
let heartbeatInterval = null;
let currentAdminPassword = '';
let soundOn = true;
let gameState = null;
let lastMultiDrawn = 0;
let lastNotificationSignature = '';

function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;}
function speakDrumNumber(n){if(!soundOn||!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(NICKNAMES[n]||String(n));u.lang='ru-RU';u.rate=1.1;window.speechSynthesis.speak(u);}
function playNotificationSound(){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C();const o=c.createOscillator();const g=c.createGain();o.frequency.value=700;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.01,c.currentTime+.25);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.25);}catch(e){}}
async function api(url,options){const r=await fetch(url,options);let data={};try{data=await r.json();}catch{}if(!r.ok)throw Object.assign(new Error(data.error||'Ошибка запроса'),{status:r.status,data});return data;}

async function loadUser(){try{const data=await api(`/api/state?uid=${encodeURIComponent(uid||'')}`);uid=data.uid;localStorage.setItem('loto_uid',uid);user=data;renderMenu();if(user.pendingGifts?.length)showGiftNotifications(user.pendingGifts);}catch(e){if(e.status===403){document.body.innerHTML='<h1 style="text-align:center;margin-top:100px;color:white">Вы заблокированы 🚫</h1>';return;}if(location.protocol==='file:'){showServerRequired();}}}
async function saveUser(patch){if(!user)return;try{const data=await api('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,...patch})});user=data.user;renderMenu();if(document.getElementById('screen-game')?.classList.contains('active'))renderGameCurrency();return true;}catch(e){alert(e.message);return false;}}
function renderMenu(){if(!user)return;const vr=document.getElementById('multi-vip-room');if(vr){vr.disabled=!user.isVip;if(!user.isVip)vr.checked=false;}const av=document.getElementById('menu-avatar-emoji');if(av){av.textContent=AVATARS[user.avatar]||AVATARS[0];av.className='avatar-emoji'+(user.isVip?' vip-avatar':'');}const nm=document.getElementById('menu-avatar-name');if(nm)nm.innerHTML=`${esc(user.name)} ${user.isVip?'<span class="vip-gold-text">👑 VIP</span>':''}`;document.getElementById('cur-bills').textContent=user.bills;document.getElementById('cur-coins').textContent=user.coins;}
function renderGameCurrency(){if(!user)return;const b=document.getElementById('game-cur-bills'),c=document.getElementById('game-cur-coins');if(b)b.textContent=user.bills;if(c)c.textContent=user.coins;}
function showServerRequired(){if(document.getElementById('server-required'))return;const d=document.createElement('div');d.id='server-required';d.innerHTML='<div class="server-required-box"><div class="server-required-logo">👑</div><h2>SANI GROUP LOTO</h2><p>Игра запущена напрямую через <b>file://</b>.</p><p>Для работы аккаунта, билетов, VIP, магазина и онлайн-столов нужен сервер.</p><p class="server-required-hint">Запустите <b>START.bat</b> из папки игры.</p><button class="btn" onclick="location.href=\'http://localhost:3000/\'">Открыть игру на сервере</button></div>';document.body.appendChild(d);}
function openModal(name){const el=document.getElementById('modal-'+name);if(!el)return;el.classList.remove('hidden');if(name==='daily')renderDaily();if(name==='vipstore')renderVipStore();if(name==='leaderboard')renderLeaderboard();if(name==='shop')renderShop();if(name==='marker')renderMarkers();if(name==='profile')renderProfile();}
function closeModal(name){document.getElementById('modal-'+name)?.classList.add('hidden');}
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));

function renderDaily(){const grid=document.getElementById('daily-grid');if(!grid)return;grid.innerHTML='';const today=(Number(user.dailyStreak)||0)%7;const can=Date.now()-Number(user.lastClaim||0)>=86400000;DAILY_REWARDS.forEach((r,i)=>{const c=document.createElement('div');c.className='daily-cell'+(i<today?' claimed':'')+(i===today?' today':'');c.innerHTML=`<div class="d-num">${i+1}</div><div class="d-icon">${r.icon}</div><div>${r.text}</div>`;grid.appendChild(c);});const b=document.getElementById('daily-claim');b.disabled=!can;b.textContent=can?'Получить награду':'Уже получено';}
document.getElementById('daily-claim').addEventListener('click',async()=>{try{const d=await api('/api/dailyreward/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid})});user=d.user;renderMenu();renderDaily();playNotificationSound();}catch(e){alert(e.message);}});
async function claimVipWeekly(){try{const d=await api('/api/vip/weekly/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid})});user=d.user;renderMenu();renderProfile();playVipGiftSound();alert(`👑 VIP-подарок: +${d.reward.bills} 💵 +${d.reward.coins} 🪙`);}catch(e){alert(e.message);}}
function renderVipStore(){const box=document.getElementById('vip-shop-list');if(!box)return;box.innerHTML='';if(!user.isVip){box.innerHTML='<div class="vip-locked">🔒 VIP STORE доступен только игрокам с VIP-статусом.</div>';return;}BARREL_DESIGNS.filter(x=>x.vip).forEach(item=>renderCosmetic(item,'barrel',box));CARD_DESIGNS.filter(x=>x.vip).forEach(item=>renderCosmetic(item,'card',box));}
function playVipGiftSound(){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),g=c.createGain(),o=c.createOscillator();o.type='sine';o.frequency.setValueAtTime(523,c.currentTime);o.frequency.exponentialRampToValueAtTime(1046,c.currentTime+.35);g.gain.setValueAtTime(.06,c.currentTime);g.gain.exponentialRampToValueAtTime(.01,c.currentTime+.55);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.55);}catch(e){}}
async function renderLeaderboard(){const list=document.getElementById('leaderboard-list');if(!list)return;list.innerHTML='Загрузка...';try{const data=await api('/api/leaderboard');list.innerHTML='';data.forEach((r,i)=>{const d=document.createElement('div');d.className='lb-row'+(r.uid===uid?' me':'');d.innerHTML=`<div class="lb-rank">${i+1}</div><div class="lb-emoji">${AVATARS[r.avatar]||'🙂'}</div><div class="lb-name">${esc(r.name)} ${r.isVip?'👑':''}</div><div class="lb-score">${r.score}</div>`;list.appendChild(d);});}catch(e){list.textContent=e.message;}}
function renderShop(){
 const list=document.getElementById('shop-list'); if(!list)return; list.innerHTML='';
 user.unlockedBarrels=user.unlockedBarrels||[0]; user.unlockedCards=user.unlockedCards||[0];
 const head=document.createElement('div'); head.className='shop-hero'; head.innerHTML='<div class="shop-hero-icon">🛍️</div><div><h3>Премиум коллекция</h3><p>Персонализируйте бочонок и игровую карточку.</p></div>'; list.appendChild(head);
 const tabs=document.createElement('div'); tabs.className='shop-tabs';
 const barrelTab=document.createElement('button'); barrelTab.className='shop-tab active'; barrelTab.textContent='🎱 Бочонки';
 const cardTab=document.createElement('button'); cardTab.className='shop-tab'; cardTab.textContent='🎟️ Карточки';
 tabs.append(barrelTab,cardTab); list.appendChild(tabs);
 const content=document.createElement('div'); content.className='shop-tab-content'; list.appendChild(content);
 const vipNote=document.createElement('div'); vipNote.className='vip-store-link-note'; vipNote.innerHTML='<span>👑</span><div><b>VIP STORE</b><small>Эксклюзивные предметы доступны только VIP. Откройте отдельный VIP STORE.</small></div><button class="btn shop-vip-open">Открыть</button>'; list.appendChild(vipNote);
 function fill(type){content.innerHTML='';const arr=type==='barrel'?BARREL_DESIGNS:CARD_DESIGNS;const title=document.createElement('div');title.className='shop-section-title';title.innerHTML=`<div><b>${type==='barrel'?'🎱 Дизайны бочонка':'🎟️ Дизайны карточки'}</b><small>${type==='barrel'?'Выберите стиль выпавшего номера':'Выберите стиль игровой карточки'}</small></div><span>${arr.filter(x=>!x.vip).length} дизайнов</span>`;content.appendChild(title);const grid=document.createElement('div');grid.className='shop-grid';arr.filter(x=>!x.vip).forEach(item=>renderCosmetic(item,type,grid));content.appendChild(grid);}
 barrelTab.onclick=()=>{barrelTab.classList.add('active');cardTab.classList.remove('active');fill('barrel');};
 cardTab.onclick=()=>{cardTab.classList.add('active');barrelTab.classList.remove('active');fill('card');};
 vipNote.querySelector('.shop-vip-open').onclick=()=>openModal('vipstore');
 fill('barrel');
}
function renderCosmetic(item,type,list){
 const owned=(type==='barrel'?user.unlockedBarrels:user.unlockedCards).includes(item.id);
 const selected=(type==='barrel'?Number(user.barrelDesign||0):Number(user.cardDesign||0))===item.id;
 const row=document.createElement('div'); row.className='shop-row cosmetic-row'+(selected?' selected':'');
 const lock=item.vip&&!user.isVip?' 🔒 VIP':'';
 const price=item.vip?'👑 VIP':(item.cost===0?'Бесплатно':item.cost+' 🪙');
 row.innerHTML=`<div class="cosmetic-preview ${type}-skin skin-${item.id}">${item.icon}</div><div class="cosmetic-info"><b>${esc(item.name)}</b><small>${price}${lock}</small></div><button class="btn small-buy">${selected?'Выбрано':owned?'Выбрать':item.vip?'Только VIP':'Купить'}</button>`;
 row.querySelector('button').addEventListener('click',async()=>{
   if(item.vip&&!user.isVip)return alert('Этот дизайн доступен только VIP-игрокам 👑');
   if(owned){try{const d=await api('/api/cosmetic/equip',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,type,id:item.id})});user=d.user;renderMenu();renderShop();}catch(e){alert(e.message)}return;}
   try{const d=await api('/api/cosmetic/buy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,type,id:item.id})});user=d.user;renderMenu();renderShop();}catch(e){alert(e.message)}
 }); list.appendChild(row);
}
function renderMarkers(){const grid=document.getElementById('marker-grid');if(!grid)return;grid.innerHTML='';user.unlockedMarkers=user.unlockedMarkers||[0];MARKERS.forEach(m=>{const owned=user.unlockedMarkers.includes(m.id);const c=document.createElement('div');c.className='marker-cell'+(user.marker===m.id?' selected':'')+(!owned?' locked':'');c.innerHTML=`<div class="m-dot" style="background:${m.color}"></div><div class="m-cost">${owned?(user.marker===m.id?'Выбран':'Выбрать'):m.cost+' 💵 🔒'}</div>`;c.addEventListener('click',async()=>{try{const d=await api('/api/marker/buy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,markerId:m.id})});user=d.user;renderMenu();renderMarkers();}catch(e){alert(e.message);}});grid.appendChild(c);});}

function renderProfile(){const weekly=document.getElementById('vip-weekly-claim');if(weekly){weekly.style.display=user.isVip?'inline-block':'none';weekly.disabled=(Date.now()-Number(user.lastVipWeeklyGift||0))<7*24*60*60*1000;weekly.textContent=weekly.disabled?'VIP-подарок ещё не доступен':'👑 Получить VIP-подарок';}const vip=document.getElementById('profile-vip');if(vip)vip.innerHTML=user.isVip?'<span class="vip-badge">👑 VIP</span>':'<span class="vip-badge vip-off">Обычный игрок</span>';const stats=document.getElementById('profile-stats');if(stats)stats.innerHTML=`<div>🏆 Побед: <b>${Number(user.wins||0)}</b></div><div>💵 Выиграно: <b>${Number(user.totalWinnings||0)}</b></div><div>🎮 Игр: <b>${Number(user.gamesPlayed||0)}</b></div>`;const input=document.getElementById('profile-name-input');input.value=user.name;document.getElementById('profile-current-avatar').textContent=AVATARS[user.avatar]||AVATARS[0];const grid=document.getElementById('avatar-grid');grid.innerHTML='';let picked=user.avatar;AVATARS.forEach((emoji,i)=>{const c=document.createElement('div');c.className='avatar-cell'+(i===picked?' selected':'');c.textContent=emoji;c.onclick=()=>{picked=i;grid.querySelectorAll('.avatar-cell').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');document.getElementById('profile-current-avatar').textContent=emoji;};grid.appendChild(c);});document.getElementById('profile-save').onclick=async()=>{const name=input.value.trim();if(!name)return alert('Ник не пустой!');if(await saveUser({name,avatar:picked}))closeModal('profile');};}

function generateTicket(){const rows=[[],[],[]];let ok=false;for(let attempt=0;attempt<20000&&!ok;attempt++){rows.forEach(r=>{r.length=0;const a=[0,1,2,3,4,5,6,7,8];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}r.push(...a.slice(0,5));});const counts=Array(9).fill(0);rows.forEach(r=>r.forEach(c=>counts[c]++));ok=counts.every(x=>x>=1&&x<=3);}if(!ok)return generateTicket();const grid=Array.from({length:3},()=>Array(9).fill(null));for(let c=0;c<9;c++){const rs=rows.map((r,i)=>r.includes(c)?i:-1).filter(i=>i>=0).sort((a,b)=>a-b);const start=c===0?1:c*10,end=c===8?90:c*10+9;const pool=[];for(let n=start;n<=end;n++)pool.push(n);pool.sort(()=>Math.random()-.5);const nums=pool.slice(0,rs.length).sort((a,b)=>a-b);rs.forEach((r,i)=>grid[r][c]=nums[i]);}return grid;}
function checkWin(mode,tickets,marks){if(mode==='A')return tickets.some((t,ti)=>t.flat().filter(Number.isInteger).every((n,idx)=>marks[ti].flat().filter(Boolean).length>=0&&isMarkedValue(n,ti,marks)));if(mode==='B')return tickets.some((t,ti)=>t.some((row,r)=>{const ns=row.filter(Number.isInteger);return ns.length&&ns.every(n=>isMarkedValue(n,ti,marks));}));if(mode==='C')return tickets.some((t,ti)=>{const ns=t[2].filter(Number.isInteger);return ns.length&&ns.every(n=>isMarkedValue(n,ti,marks));});return false;}
function isMarkedValue(n,ti,marks){const ticket=gameState.tickets[ti];for(let r=0;r<3;r++)for(let c=0;c<9;c++)if(ticket[r][c]===n)return !!marks[ti][r][c];return false;}
function markedValues(){const out=[];if(!gameState)return out;gameState.tickets.forEach((t,ti)=>t.forEach((row,r)=>row.forEach((n,c)=>{if(Number.isInteger(n)&&gameState.marks[ti][r][c])out.push(n);})));return [...new Set(out)];}
function renderTickets(){const container=document.getElementById('tickets-container');if(!container||!gameState)return;container.innerHTML='';const marker=(MARKERS.find(m=>m.id===user.marker)||MARKERS[0]).color;gameState.tickets.forEach((ticket,ti)=>{const table=document.createElement('table');table.className='ticket card-skin-'+Number(user.cardDesign||0)+(user.isVip?' vip-ticket':'');ticket.forEach((row,ri)=>{const tr=document.createElement('tr');row.forEach((v,ci)=>{const td=document.createElement('td');if(v===null){td.className='empty';}else{td.textContent=v;if(gameState.marks[ti][ri][ci]){td.classList.add('marked');td.style.background=marker;}else if(gameState.drawn.includes(v))td.classList.add('drawn-not-marked');td.onclick=()=>{if(gameState.drawn.includes(v)&&!gameState.marks[ti][ri][ci]){gameState.marks[ti][ri][ci]=true;renderTickets();maybeClaimMultiWin();}};}tr.appendChild(td);});table.appendChild(tr);});container.appendChild(table);});}
function updateHistoryUI(){const h=document.getElementById('history-numbers');if(!h||!gameState)return;h.innerHTML=gameState.drawn.slice(-5).reverse().map(n=>`<span class="history-item">${n}</span>`).join(' ');}
function playVipDrawSound(){if(!soundOn||!user?.isVip)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),g=c.createGain(),o=c.createOscillator();o.type='triangle';o.frequency.value=880;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.005,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16);}catch(e){}}
function showNumber(n){playVipDrawSound();const drum=document.getElementById('drum-number');if(drum)drum.className='drum skin-'+Number(user?.barrelDesign||0)+(user?.isVip?' vip-drum':'');const el=document.getElementById('drum-number');el.textContent=n;el.style.animation='none';void el.offsetHeight;el.style.animation='popDrum .4s ease-out';document.getElementById('drum-nickname').textContent=NICKNAMES[n]||'';}
async function sendGameStat(action){try{await api('/api/game/stat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,action})});}catch(e){}}
function startGame(mode,numCards){document.getElementById('screen-menu').classList.remove('active');document.getElementById('screen-game').classList.add('active');document.getElementById('room-chat-container').classList.add('hidden');renderGameCurrency();const ga=document.getElementById('game-player-avatar');ga.textContent=AVATARS[user.avatar]||AVATARS[0];ga.className='avatar-emoji'+(user.isVip?' vip-avatar':'');document.getElementById('game-player-name').innerHTML=esc(user.name)+(user.isVip?' <span class="vip-gold-text">👑 VIP</span>':'');document.getElementById('screen-game').classList.toggle('vip-table',!!user.isVip);const tickets=[],marks=[];for(let i=0;i<numCards;i++){tickets.push(generateTicket());marks.push(Array.from({length:3},()=>Array(9).fill(false)));}gameState={mode,tickets,marks,drawn:[],timer:null,finished:false};sendGameStat('start');renderTickets();gameState.timer=setInterval(()=>{if(gameState.drawn.length>=90){clearInterval(gameState.timer);return;}let n;do n=Math.floor(1+Math.random()*90);while(gameState.drawn.includes(n));gameState.drawn.push(n);showNumber(n);speakDrumNumber(n);updateHistoryUI();renderTickets();if(checkWin(mode,tickets,marks)){clearInterval(gameState.timer);triggerWinEffects(mode==='A'?'🎉 Вы победили!':mode==='B'?'🎉 Короткое Лото — вы закрыли строку!':'🎉 Три на Три — вы закрыли нижнюю строку!');}},DRAW_INTERVAL);}
function triggerWinEffects(msg){if(gameState&&!gameState.statWin&&!gameState.multi){gameState.statWin=true;sendGameStat('win');}playNotificationSound();document.body.classList.add('vip-win');setTimeout(()=>document.body.classList.remove('vip-win'),1800);const overlay=document.createElement('div');overlay.className='win-overlay'+(user?.isVip?' vip-win-overlay':'');overlay.innerHTML=`<div>${user?.isVip?'👑 VIP WIN':'🎉'}</div><small>${esc(msg)}</small>`;document.body.appendChild(overlay);setTimeout(()=>overlay.remove(),1900);setTimeout(()=>alert(msg),300);}

function openMultiplayer(){document.getElementById('modal-multiplayer').classList.remove('hidden');document.getElementById('multi-create-block').classList.remove('hidden');document.getElementById('multi-join-block').classList.remove('hidden');document.getElementById('multi-waiting-block').classList.add('hidden');}
document.getElementById('btn-open-multiplayer').addEventListener('click',openMultiplayer);
document.getElementById('btn-close-multiplayer').addEventListener('click',()=>{closeModal('multiplayer');stopMultiTimers();});
document.getElementById('btn-multi-create').addEventListener('click',async()=>{try{stopMultiTimers();const maxPlayers=Number(document.getElementById('multi-max-players').value);const stake=Number(document.getElementById('multi-stake').value);const mode=document.querySelector('input[name="game-mode"]:checked')?.value||'A';const d=await api('/api/room/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,maxPlayers,stake,mode,vipOnly:document.getElementById('multi-vip-room')?.checked===true})});user.bills=d.userBalance;renderMenu();startWaiting(d.roomId);}catch(e){alert(e.message);}});
document.getElementById('btn-multi-join').addEventListener('click',async()=>{try{stopMultiTimers();const roomId=document.getElementById('multi-room-id').value.trim();if(!roomId)return alert('Введите код стола');const d=await api('/api/room/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId})});user.bills=d.userBalance;renderMenu();startWaiting(roomId);}catch(e){alert(e.message);}});
function startWaiting(roomId){currentRoomId=String(roomId);document.getElementById('multi-create-block').classList.add('hidden');document.getElementById('multi-join-block').classList.add('hidden');document.getElementById('multi-waiting-block').classList.remove('hidden');document.getElementById('txt-table-code').textContent=currentRoomId;syncRoom();multiSyncInterval=setInterval(syncRoom,1000);heartbeatInterval=setInterval(sendHeartbeat,4000);}
function stopMultiTimers(){if(multiSyncInterval){clearInterval(multiSyncInterval);multiSyncInterval=null;}if(heartbeatInterval){clearInterval(heartbeatInterval);heartbeatInterval=null;}}
async function sendHeartbeat(){if(!currentRoomId)return;try{await api('/api/room/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId})});}catch(e){}}
async function syncRoom(){if(!currentRoomId)return;try{const room=await api(`/api/room/sync?roomId=${encodeURIComponent(currentRoomId)}&uid=${encodeURIComponent(uid)}`);document.getElementById('multi-players-list').innerHTML=room.players.map(p=>`<div>🧑‍💻 ${esc(p.name)} ${p.online?'🟢':'⚪'}</div>`).join('');if(room.status==='playing'){document.getElementById('modal-multiplayer').classList.add('hidden');startMultiGame(room);}else if(room.status==='finished'||room.status==='cancelled'){stopMultiTimers();alert(room.winnerUid===uid?`🎉 Вы выиграли ${room.payout} 💵!`:'Стол завершён.');location.reload();}}catch(e){if(e.status===404){stopMultiTimers();alert('Стол больше не существует.');location.reload();}}}
function startMultiGame(room){stopMultiTimers();currentRoomId=room.id;document.getElementById('screen-menu').classList.remove('active');document.getElementById('screen-game').classList.add('active');document.getElementById('room-chat-container').classList.remove('hidden');gameState={mode:room.mode,tickets:[room.selfTicket],marks:[Array.from({length:3},()=>Array(9).fill(false))],drawn:room.drawn||[],finished:false,multi:true};lastMultiDrawn=gameState.drawn[gameState.drawn.length-1]||0;renderTickets();if(lastMultiDrawn)showNumber(lastMultiDrawn);updateHistoryUI();multiSyncInterval=setInterval(syncMultiGame,1000);heartbeatInterval=setInterval(sendHeartbeat,4000);}
async function syncMultiGame(){try{const room=await api(`/api/room/sync?roomId=${encodeURIComponent(currentRoomId)}&uid=${encodeURIComponent(uid)}`);if(room.drawn.length>gameState.drawn.length){gameState.drawn=room.drawn;const n=room.drawn[room.drawn.length-1];showNumber(n);speakDrumNumber(n);playNotificationSound();updateHistoryUI();renderTickets();if(n!==lastMultiDrawn)lastMultiDrawn=n;}if(room.chat){document.getElementById('room-chat-messages').innerHTML=room.chat.map(m=>`<div><b>${esc(m.name)} ${m.isVip?'👑 VIP':''}:</b> ${esc(m.text)}</div>`).join('');}if(room.status==='finished'||room.status==='cancelled'){stopMultiTimers();if(room.winnerUid===uid)triggerWinEffects(`🎉 Вы выиграли ${room.payout} 💵!`);else alert(room.status==='cancelled'?'Игра отменена, ставки возвращены.':'Игра завершена.');setTimeout(()=>location.reload(),800);return;}await maybeClaimMultiWin();}catch(e){}}
async function maybeClaimMultiWin(){if(!gameState?.multi||gameState.finished)return;if(!checkWin(gameState.mode,gameState.tickets,gameState.marks))return;gameState.finished=true;try{const d=await api('/api/room/win',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId,marked:markedValues()})});stopMultiTimers();user.bills=d.userBalance;renderMenu();triggerWinEffects(`🎉 Вы выиграли ${d.payout} 💵 и забрали банк!`);setTimeout(()=>location.reload(),1200);}catch(e){gameState.finished=false;}}

document.getElementById('btn-open-global-chat').addEventListener('click',()=>{openModal('global-chat');updateGlobalChat();});document.getElementById('btn-close-global-chat').addEventListener('click',()=>closeModal('global-chat'));
document.getElementById('btn-room-chat-send').addEventListener('click',async()=>{const i=document.getElementById('room-chat-input');if(!i.value.trim())return;try{await api('/api/chat/room/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId,text:i.value.trim()})});i.value='';await syncMultiGame();}catch(e){alert(e.message);}});
document.getElementById('btn-global-chat-send').addEventListener('click',async()=>{const i=document.getElementById('global-chat-input');if(!i.value.trim())return;try{await api('/api/chat/global/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,text:i.value.trim()})});i.value='';updateGlobalChat();}catch(e){alert(e.message);}});
async function updateGlobalChat(){const box=document.getElementById('global-chat-messages');if(!box||document.getElementById('modal-global-chat').classList.contains('hidden'))return;try{const data=await api('/api/chat/global');box.innerHTML=data.map(m=>`<div><b>${esc(m.name)} ${m.isVip?'👑 VIP':''}:</b> ${esc(m.text)}</div>`).join('');box.scrollTop=box.scrollHeight;}catch(e){}}

function showGiftNotifications(gifts){if(!gifts?.length)return;const sig=gifts.map(g=>`${g.at||0}:${g.type||''}:${g.message||''}:${g.bills||0}:${g.coins||0}`).join('|');if(sig===lastNotificationSignature)return;lastNotificationSignature=sig;playNotificationSound();const latest=[...gifts].sort((a,b)=>(a.at||0)-(b.at||0));const g=latest[latest.length-1];const modal=document.getElementById('modal-gift-alert');const icon=document.getElementById('gift-icon');const title=document.getElementById('gift-title');const sender=document.getElementById('gift-sender');const bills=document.getElementById('gift-alert-bills');const coins=document.getElementById('gift-alert-coins');icon.textContent=g.type==='vip'?'👑':g.type==='message'?'💬':'🎁';title.textContent=g.type==='vip'?'VIP-уведомление':g.type==='message'?'SMS от SANI GROUP':'Вам подарок!';sender.textContent=g.message||'Получено от: SANI GROUP';bills.textContent=g.bills?`+${g.bills} 💵`:'';coins.textContent=g.coins?`+${g.coins} 🪙`:'';modal.classList.remove('hidden');document.getElementById('btn-close-gift-alert').onclick=async()=>{modal.classList.add('hidden');try{const d=await api('/api/notifications/clear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid})});user=d.user;renderMenu();}catch(e){}};}

document.getElementById('btn-admin-login').addEventListener('click',()=>openModal('admin'));document.getElementById('btn-close-admin').addEventListener('click',()=>closeModal('admin'));document.getElementById('btn-admin-auth').addEventListener('click',async()=>{currentAdminPassword=document.getElementById('admin-password-input').value;await refreshAdminPanel();});
async function refreshAdminPanel(){try{const players=await api('/api/admin/players',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminPassword:currentAdminPassword})});document.getElementById('admin-auth-block').classList.add('hidden');document.getElementById('admin-panel-block').classList.remove('hidden');renderAdminPlayers(players);}catch(e){alert('Пароль неверный!');}}
function renderAdminPlayers(players){const box=document.getElementById('admin-players-list');box.innerHTML='';players.forEach(p=>{const d=document.createElement('div');d.className='admin-player';d.innerHTML=`<div class="admin-player-head"><b>${esc(p.name)}</b><span>${p.isVip?'👑 VIP':''} ${p.isBanned?'🛑 БАН':''}</span></div><div>💵 ${p.bills} &nbsp; 🪙 ${p.coins}</div><div class="admin-actions"><button data-a="money">💵 Деньги</button><button data-a="coins">🪙 Монеты</button><button data-a="message">💬 SMS</button><button data-a="vip">${p.isVip?'❌ VIP':'👑 VIP'}</button><button data-a="ban">${p.isBanned?'🔓 Разбан':'🔒 Бан'}</button></div>`;d.querySelector('[data-a="money"]').onclick=()=>adminAmount(p.uid,'money');d.querySelector('[data-a="coins"]').onclick=()=>adminAmount(p.uid,'coins');d.querySelector('[data-a="message"]').onclick=()=>adminMessage(p.uid);d.querySelector('[data-a="vip"]').onclick=()=>adminAction(p.uid,'vip',{enabled:!p.isVip});d.querySelector('[data-a="ban"]').onclick=()=>adminAction(p.uid,p.isBanned?'unban':'ban');box.appendChild(d);});let clear=document.getElementById('admin-clear-db');if(clear)clear.onclick=async()=>{if(confirm('Удалить ВСЮ базу игроков и активные столы?'))if(confirm('Последнее подтверждение: восстановить данные будет нельзя. Продолжить?')){await adminAction(null,'clear_database');location.reload();}};}
async function adminAmount(id,action){const amount=Number(prompt(action==='money'?'Сколько 💵 выдать?':'Сколько 🪙 выдать?'));if(!Number.isInteger(amount)||amount<=0)return;await adminAction(id,action,{amount});}
async function adminMessage(id){const message=prompt('Текст SMS игроку:');if(!message?.trim())return;await adminAction(id,'message',{message:message.trim()});}
async function adminAction(id,action,extra={}){try{await api('/api/admin/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminPassword:currentAdminPassword,uid:id,action,...extra})});if(action!=='clear_database')await refreshAdminPanel();}catch(e){alert(e.message);}}

document.getElementById('vip-weekly-claim')?.addEventListener('click',claimVipWeekly);
document.getElementById('btn-play').addEventListener('click',()=>{if(!user)return showServerRequired();openModal('setup');});document.getElementById('setup-start').addEventListener('click',()=>{closeModal('setup');startGame(document.querySelector('input[name="game-mode"]:checked')?.value||'A',3);});
document.getElementById('btn-exit-game').addEventListener('click',async()=>{if(currentRoomId)try{await api('/api/room/leave',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid,roomId:currentRoomId})});}catch(e){}stopMultiTimers();currentRoomId=null;location.reload();});
document.getElementById('btn-sound').addEventListener('click',e=>{soundOn=!soundOn;e.target.textContent=soundOn?'🔊':'🔇';});
setInterval(()=>{if(document.getElementById('modal-global-chat')&&!document.getElementById('modal-global-chat').classList.contains('hidden'))updateGlobalChat();},2000);
setInterval(loadUser,5000);
loadUser();
